server:
  port: 8081

spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    timeout: 3000
    lettuce:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  aop:
    proxy-target-class: true

# knife4j 配置
knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
    enable-version: false
    enable-reload-cache-parameter: false
    enable-after-script: true
    enable-filter-multipart-api-method-type: POST
    enable-filter-multipart-apis: false
    enable-request-cache: true
    enable-host: false
    enable-host-text: ""
    enable-home-custom: false
    home-custom-path: ""
    enable-search: true
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: Apache License 2.0 | Copyright  2020-[knife4j](https://github.com/xiaoymin/knife4j)
    enable-dynamic-parameter: false
    enable-debug: true
    enable-open-api: false
    enable-group: true

mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/**/*.xml
  configuration:
    local-cache-scope: STATEMENT
    cache-enabled: false
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: NONE

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

socket:
  max-frame-payload-length: 1048576
  max-http-content-length: 1048576

alioss:
  endpoint: ${sky.alioss.endpoint}
  access-key-id: ${sky.alioss.access-key-id}
  access-key-secret: ${sky.alioss.access-key-secret}
  bucket-name: ${sky.alioss.bucket-name}